`ifndef MCST_LAB_DSP_GPU_INSNMODES_DEF_V
`define MCST_LAB_DSP_GPU_INSNMODES_DEF_V

`define SET_CONST_MODE_REG 8
`define SET_CONST_MODE_CONST 1
`define SET_CONST_MODE_CORE_ID 0

`define ENABLE_WRITE 2'b10
`define ENABLE_READ 2'b01

`endif //MCST_LAB_DSP_GPU_INSNMODES_DEF_V